//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGSA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KGSA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Address_Book {
            get {
                object obj = ResourceManager.GetObject("Address_Book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Next_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Next_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Next_16xLG_color {
            get {
                object obj = ResourceManager.GetObject("arrow_Next_16xLG_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Next_16xLG_color1 {
            get {
                object obj = ResourceManager.GetObject("arrow_Next_16xLG_color1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Next_16xLG_colorB {
            get {
                object obj = ResourceManager.GetObject("arrow_Next_16xLG_colorB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Next_16xLG_colorG {
            get {
                object obj = ResourceManager.GetObject("arrow_Next_16xLG_colorG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjon 2.8 Beta - 03.07.2015 BETA
        ///
        ///Veldig mange endringer siden sist versjon var utgitt. Alt for mange å nevne her :)
        ///I korthet har det blitt trimmet ned på noen funksjoner og fjernet helt andre for så å bytte det ut med noe annet.
        ///Det er første gang jeg gikk til dette skrittet, men det trengs etter lang tids feature creep og bloat.
        ///
        ///Først det som er fjernet helt:
        ///- Eksportering av bilder for fremvisning er fjernet helt. Svært vanskelig å få til riktig og alt for mye arbeid ved å holde det ved like. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Elkjoplogo {
            get {
                object obj = ResourceManager.GetObject("Elkjoplogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Elkjoplogo_Bg {
            get {
                object obj = ResourceManager.GetObject("Elkjoplogo_Bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emailButton {
            get {
                object obj = ResourceManager.GetObject("emailButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Ever {
            get {
                object obj = ResourceManager.GetObject("Ever", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F1Help_7644 {
            get {
                object obj = ResourceManager.GetObject("F1Help_7644", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear_32xLG {
            get {
                object obj = ResourceManager.GetObject("gear_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap htmleditor_preview_icon {
            get {
                object obj = ResourceManager.GetObject("htmleditor_preview_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&apos;text/javascript&apos; src=&apos;jquery.js&apos;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos; src=&apos;jquery.metadata.js&apos;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos; src=&apos;jquery.tablesorter.js&apos;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos;&gt;
        ///
        ///$(document).ready(function() {		
        ///	$(&quot;.tablesorter&quot;).tablesorter(
        ///	{
        ///		emptyTo: &apos;zero&apos;,
        ///		stringTo: &quot;zero&quot;,
        ///		widgets: [&apos;zebra&apos;],
        ///		sortReset   : true,
        ///		dateFormat : &quot;mm.dd.yyyy&quot;
        ///	}
        ///	);   
        ///});
        ///
        ///$(document).ready(function(){
        ///    $(&apos;.image&apos;).click(function(){
        ///		$(this). [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlEnd {
            get {
                return ResourceManager.GetString("htmlEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body {
        ///	font-weight:400;
        ///	font-family:Calibri, sans-serif;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Noe galt skjedde under arbeidet med å lage denne siden... :(&lt;/span&gt;&lt;br&gt;&lt;span class=&apos;xHea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlError {
            get {
                return ResourceManager.GetString("htmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body
        ///{
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10;
        ///	background-color: #ffffff;
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///.xContent
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Ingen transaksjo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlImportData {
            get {
                return ResourceManager.GetString("htmlImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body
        ///{
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10;
        ///	background-color: #ffffff;
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///.xContent
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Ingen servicer f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlImportService {
            get {
                return ResourceManager.GetString("htmlImportService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body
        ///{
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10;
        ///	background-color: #ffffff;
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///.xContent
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Ingen lagerdata  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlImportStore {
            get {
                return ResourceManager.GetString("htmlImportStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body {
        ///	font-weight:400;
        ///	font-family:Calibri, sans-serif;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Laster, vent litt..&lt;/span&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string htmlLoading {
            get {
                return ResourceManager.GetString("htmlLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body {
        ///	font-weight:400;
        ///	font-family:Calibri, sans-serif;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Budsjett mangler for valgt kategori.&lt;/span&gt;&lt;br&gt;&lt;span class=&apos;xHeader&apos;&gt;Gå til Verktøy -&gt; B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlSetupBudget {
            get {
                return ResourceManager.GetString("htmlSetupBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body {
        ///	font-weight:400;
        ///	font-family:Calibri, sans-serif;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///.xHeaderRed
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlStopped {
            get {
                return ResourceManager.GetString("htmlStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_fileTypePdf_16x18px {
            get {
                object obj = ResourceManager.GetObject("icon_fileTypePdf_16x18px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] img_bar_green {
            get {
                object obj = ResourceManager.GetObject("img_bar_green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] img_bar_red {
            get {
                object obj = ResourceManager.GetObject("img_bar_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.0 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k=&quot;&quot;.trim,l={},m=&quot;1.11.0&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Metadata - jQuery plugin for parsing metadata from elements
        /// *
        /// * Copyright (c) 2006 John Resig, Yehuda Katz, Jörn Zaefferer, Paul McLanahan
        /// *
        /// * Dual licensed under the MIT and GPL licenses:
        /// *   http://www.opensource.org/licenses/mit-license.php
        /// *   http://www.gnu.org/licenses/gpl.html
        /// *
        /// */
        ///
        ////**
        /// * Sets the type of metadata to use. Metadata is encoded in JSON, and each property
        /// * in the JSON will become a property of the element itself.
        /// *
        /// * There are three supported types of metadata storage: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_metadata {
            get {
                return ResourceManager.GetString("jquery_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**!
        ///* TableSorter 2.14.5 - Client-side table sorting with ease!
        ///* @requires jQuery v1.2.6+
        ///*
        ///* Copyright (c) 2007 Christian Bach
        ///* Examples and docs at: http://tablesorter.com
        ///* Dual licensed under the MIT and GPL licenses:
        ///* http://www.opensource.org/licenses/mit-license.php
        ///* http://www.gnu.org/licenses/gpl.html
        ///*
        ///* @type jQuery
        ///* @name tablesorter
        ///* @cat Plugins/Tablesorter
        ///* @author Christian Bach/christian.bach@polyester.se
        ///* @contributor Rob Garrison/https://github.com/Mottie/tablesorter
        ///*/
        ////*jshint  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_tablesorter {
            get {
                return ResourceManager.GetString("jquery_tablesorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&apos;text/javascript&apos;&gt;
        ///
        ///function confirmAction() {
        ///    var confirmed = confirm(&quot;Prosessen er ikke mulig å kanselere etter at den er startet\nEr du sikker?&quot;);
        ///    return confirmed;
        ///}
        ///
        ///function confirmRemove() {
        ///    var confirmed = confirm(&quot;Dette vil slette valgt element.\nEr du sikker?&quot;);
        ///    return confirmed;
        ///}
        ///
        ///$(function () {
        ///    $(&quot;#submit&quot;).click(function () {
        ///        if (confirm(&quot;Click OK to continue?&quot;)) {
        ///            $(&apos;form#settings&apos;).submit();
        ///        }
        ///        else
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsWeb {
            get {
                return ResourceManager.GetString("jsWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KPI_16xLG {
            get {
                object obj = ResourceManager.GetObject("KPI_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KPI_16xLG_color1 {
            get {
                object obj = ResourceManager.GetObject("KPI_16xLG_color1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KPI_16xLG_color3 {
            get {
                object obj = ResourceManager.GetObject("KPI_16xLG_color3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KPI_16xLG_colorG {
            get {
                object obj = ResourceManager.GetObject("KPI_16xLG_colorG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lefdal_Bg {
            get {
                object obj = ResourceManager.GetObject("Lefdal_Bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap library_16xLG {
            get {
                object obj = ResourceManager.GetObject("library_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lines_Text_code_16xLG {
            get {
                object obj = ResourceManager.GetObject("lines_Text_code_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lines_Text_justify_16xLG {
            get {
                object obj = ResourceManager.GetObject("lines_Text_justify_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linesplot {
            get {
                object obj = ResourceManager.GetObject("linesplot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_16xLG {
            get {
                object obj = ResourceManager.GetObject("list_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start({elguide}) // Makro for uthening av transaksjoner
        ///WaitForTitle(elguide)
        ///Wait(5)
        ///KeyString(brukernavn)
        ///KeyPress(Enter)
        ///Password(063076096091137154182008082147210214147164196053)
        ///KeyPress(Enter)
        ///Wait(5)
        ///KeyString(137)
        ///KeyPress(Enter) // åpner ranking program
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyString({dato}) // Fra-dato
        ///KeyPress(Enter) // Hopp over til-dato
        ///KeyPress(Enter)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macro_img_sign {
            get {
                object obj = ResourceManager.GetObject("macro_img_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start({elguide}) // Makro for uthenting av kveldstall
        ///WaitForTitle(elguide) // Vent på at elguide åpner seg
        ///Wait(5)
        ///KeyString(brukernavn)
        ///KeyPress(Enter)
        ///Password(063076096091137154182008082147210214147164196053)
        ///KeyPress(Enter)
        ///Wait(5) // Her må vi være i elguide hovedmenyen, resten blir dynamisk generert
        ///ImportKveldstall().
        /// </summary>
        internal static string MacroQuick {
            get {
                return ResourceManager.GetString("MacroQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start({elguide}) // Makro for uthenting av service logg
        ///WaitForTitle(elguide)
        ///Wait(5)
        ///KeyString(brukernavn)
        ///KeyPress(Enter)
        ///Password(063076096091137154182008082147210214147164196053)
        ///KeyPress(Enter)
        ///Wait(5)
        ///KeyString(244) // Velger forespørsel program
        ///KeyPress(Enter) // åpner program
        ///KeyPress(Down)
        ///KeyPress(Enter)
        ///KeyPress(Enter) // hopper over avdeling
        ///KeyString({fradato})
        ///KeyPress(Enter)
        ///KeyString({tildato})
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter)
        ///KeyPress(Enter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacroService {
            get {
                return ResourceManager.GetString("MacroService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start({elguide}) // Makro for uthenting av lager data
        ///WaitForTitle(elguide)
        ///Wait(5)
        ///KeyString(brukernavn)
        ///KeyPress(Enter)
        ///Password(063076096091137154182008082147210214147164196053)
        ///KeyPress(Enter)
        ///Wait(5) 
        ///KeyString(115)
        ///KeyPress(Enter)
        ///Wait(3)
        ///KeyString(brukernavn)
        ///KeyPress(Enter)
        ///Password(063076096091137154182008082147210214147164196053)
        ///KeyPress(Enter)
        ///KeyString({avdeling})
        ///KeyPress(Enter)
        ///KeyPress(Enter) // Datoen
        ///KeyPress(Enter) // Start
        ///Wait(10)
        ///KeyPress(F12)
        ///KeyPress(Right)
        ///KeyP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacroStore {
            get {
                return ResourceManager.GetString("MacroStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Message_16xLG {
            get {
                object obj = ResourceManager.GetObject("Message_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyElkjopLogo3 {
            get {
                object obj = ResourceManager.GetObject("nyElkjopLogo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Output_16xLG {
            get {
                object obj = ResourceManager.GetObject("Output_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pdf_icon {
            get {
                object obj = ResourceManager.GetObject("pdf_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PencilAngled_16xLG_color {
            get {
                object obj = ResourceManager.GetObject("PencilAngled_16xLG_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer_16xLG {
            get {
                object obj = ResourceManager.GetObject("printer_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap procedure_16xLG {
            get {
                object obj = ResourceManager.GetObject("procedure_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16xLG {
            get {
                object obj = ResourceManager.GetObject("refresh_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resource_16xLG {
            get {
                object obj = ResourceManager.GetObject("resource_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rows1 {
            get {
                object obj = ResourceManager.GetObject("rows1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSReport_16xLG {
            get {
                object obj = ResourceManager.GetObject("RSReport_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save1 {
            get {
                object obj = ResourceManager.GetObject("Save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_16xLG {
            get {
                object obj = ResourceManager.GetObject("script_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Services_16xLG {
            get {
                object obj = ResourceManager.GetObject("Services_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sk {
            get {
                object obj = ResourceManager.GetObject("sk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Step_16xLG {
            get {
                object obj = ResourceManager.GetObject("Step_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style id=&quot;stylesheet&quot;&gt;
        ///
        ///@media print
        ///{    
        ///    .no-print, .no-print *, .toolbox, .main-menu
        ///    {
        ///        display: none !important;
        ///    }
        ///
        ///}
        ///
        ///.no-break {
        ///    page-break-inside:avoid;
        ///}
        ///
        ///h2 {
        ///    page-break-before:always;
        ///}
        ///
        ///h1 + h2 {
        ///    page-break-before:avoid;
        ///}
        ///
        ///h3, h4, h5 {
        ///    page-break-before:avoid;
        ///}
        ///
        ///h2 + div, h3 + div, h2 + table, h3 + table {
        ///    page-break-inside:avoid;
        ///}
        ///
        ///.page-break {
        ///  overflow: hidden;
        ///  page-break-after: auto;
        ///}
        ///
        ///header { 
        ///    z-index:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Symbols_Help_and_inclusive_16xLG {
            get {
                object obj = ResourceManager.GetObject("Symbols_Help_and_inclusive_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;form name=&quot;form1&quot; method=&quot;post&quot; action=&quot;?submit&quot;&gt;
        ///&lt;p&gt;Textarea test:&lt;/p&gt;
        ///&lt;p&gt;
        ///  &lt;textarea name=&quot;textcontent&quot; id=&quot;textcontent&quot; cols=&quot;60&quot; rows=&quot;5&quot;&gt;&lt;/textarea&gt;
        ///&lt;/p&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;5&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Text test 1:&lt;/td&gt;
        ///    &lt;td&gt;&lt;input type=&quot;text&quot; name=&quot;webserverUser&quot; id=&quot;webserverUser&quot;&gt;&lt;/td&gt;
        ///    &lt;td&gt;Text test 2:&lt;/td&gt;
        ///    &lt;td&gt;&lt;input type=&quot;text&quot; name=&quot;webserverPassword&quot; id=&quot;webserverPassword&quot;&gt;&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Select test 1:&lt;/td&gt;
        ///    &lt;td&gt;&lt;select name=&quot;importSetti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebFormTest {
            get {
                return ResourceManager.GetString("WebFormTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;KGSA&lt;/title&gt;
        ///&lt;style id=&apos;sheet&apos;&gt;
        ///
        ///body
        ///{
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10px;
        ///	background-color: #ffffff;
        ///}
        ///
        ///.xHeader
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///.xContent
        ///{
        ///	font-size:11.0pt;
        ///	font-weight:400;
        ///	font-style:normal;
        ///	text-decoration:none;
        ///	font-family:Calibri, sans-serif;
        ///}
        ///
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;span class=&apos;xHeader&apos;&gt;Velommen til K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webserver_menu {
            get {
                return ResourceManager.GetString("webserver_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style id=&quot;stylesheet&quot;&gt;
        ///
        ///
        ///    .Settings
        ///    {
        ///        border: #aaa 1px solid;
        ///        background-color: white;
        ///        color: black;
        ///    }
        ///
        ///    .Table
        ///    {
        ///        display: table;
        ///        border-collapse:collapse;
        ///    }
        ///    .Title
        ///    {
        ///        display: table-caption;
        ///        text-align: center;
        ///        font-weight: bold;
        ///        font-size: larger;
        ///    }
        ///    .Heading
        ///    {
        ///        display: table-row;
        ///        font-weight: bold;
        ///        text-align: center;
        ///        color:black;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webstyle {
            get {
                return ResourceManager.GetString("webstyle", resourceCulture);
            }
        }
    }
}
